// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Task$MyResApp from "./Task.bs.js";
import * as Hooks$MyResApp from "./Hooks.bs.js";
import * as Header$MyResApp from "./Header.bs.js";
import * as AddTask$MyResApp from "./AddTask.bs.js";

function TaskTracker(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setShowAddTask = match[1];
  var showAddTask = match[0];
  var toogleShowAddTask = function (param) {
    return Curry._1(setShowAddTask, (function (prev) {
                  return !prev;
                }));
  };
  var todos = Hooks$MyResApp.useObservableValue(Task$MyResApp.defaultTasksSubject, Task$MyResApp.defaultTasks);
  var addTask = function (task) {
    Task$MyResApp.defaultTasksSubject.next(Belt_Array.concat(todos, [task]));
    
  };
  var deleteTask = function (id) {
    Task$MyResApp.defaultTasksSubject.next(todos.filter(function (task) {
              return task.id !== id;
            }));
    
  };
  var toggleReminder = function (id) {
    Task$MyResApp.defaultTasksSubject.next(todos.map(function (task) {
              if (task.id === id) {
                return {
                        id: task.id,
                        text: task.text,
                        day: task.day,
                        reminder: !task.reminder
                      };
              } else {
                return task;
              }
            }));
    
  };
  return React.createElement("div", undefined, React.createElement(Header$MyResApp.make, {
                  showAddTask: showAddTask,
                  toogleShowAddTask: toogleShowAddTask,
                  title: "Task Tracker"
                }), showAddTask ? React.createElement(AddTask$MyResApp.make, {
                    addTask: addTask
                  }) : null, React.createElement("div", undefined, todos.map(function (task) {
                      return React.createElement(Task$MyResApp.make, {
                                  task: task,
                                  toggleReminder: toggleReminder,
                                  deleteTask: deleteTask,
                                  key: task.id
                                });
                    })));
}

var make = TaskTracker;

export {
  make ,
  
}
/* react Not a pure module */
